name: dotnet build 
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/dotnetbuild.yml
      - HelloWorldApp

jobs:
  HelloWorldApp_BasicProject:
    name: Compiling HelloWorldApplication
    runs-on: ubuntu-latest

    steps:
      - name: Chekcout the sourcecode
        uses: actions/checkout@v4

      - name: List all the files
        run: ls -l

      - name: Build the HelloWorldApplication
        run: dotnet build --configuration Release

      - name: Lista all the files
        run: ls -l
