name: Deploy DotnetBuild Output
on:
  push:
    branches: 
      - srinivas_patch
    paths:
      - .github/workflows/dotnetdeploy.yml

jobs:
  Deploy_DotnetBuildOutput:
    name: Deploy the Output files
    runs-on: ubuntu-latest

    steps:
      - name: Deploy the artifacts
        uses: actions/download-artifact@v4
        with:
          name: Hello-World-App
          path: Hello-World-App

      - name: List all the downloaded artifacts
        run: ls -R Hello-World-All
  
