name: dotnet build 
on:
  push:
    branches:
      - srinivas_patch
    paths:
      - .github/workflows/dotnetbuild.yml
      - HelloWorldApp

jobs:
  HelloWorldApp_BasicProject:
    name: Compiling HelloWorldApplication
    runs-on: ubuntu-latest

    steps:
      - name: Chekcout the sourcecode
        uses: actions/checkout@v4
      - name: List all the files
        run: ls -la

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Display .NET SDK Version
        run: dotnet --version

      - name: Build the HelloWorldApplication
        run: dotnet build HelloWorldApp/HelloWorldApp.sln --configuration Release --verbosity normal

      - name: Run the HelloWorldApplication
        run: |
          cd HelloWorldApp
          dotnet run

      - name: Display the GitHubWorkspace
        run: echo "$GITHUB_WORKSPACE"

      - name: Lista all the files
        run: ls -la

      - name: Upload BuildArtifacts
        uses: actions/upload-artifact@v4
        with:
          name: Hello-World-App
          path: ${{github.workspace}}/HelloWorldApp/bin/Release/**
