name: Deploy DotnetBuild Output
on:
  push:
    branches: 
      - srinivas_patch
    paths:
      - .github/workflows/dotnetdeploy.yml

jobs:
  Deploy_DotnetBuildOutput:
    name: Deploy the Output files
    runs-on: ubuntu-latest

    steps:
      - name: Display the GitHubToken information
        run: echo "${{github.token}}"
        
      - name: Deploy the artifacts
        uses: actions/download-artifact@v4
        with:
          name: Hello-World-App
          path: Hello-World-App
          github-token: ${{github.token}}
          run-id: 14166713720

      - name: List all the downloaded artifacts
        run: |
          ls -R Hello-World-App"
          pwd

      - name: Find the actual dll path
        run: |
          cd Hello-World-App
          # Find the actual DLL path
          find . -name "*.dll" -type f
          
      - name: Run the HelloWorldApplication
        run: |
          cd Hello-World-App
          dotnet HelloWorldApp.dll
  
